spring.application.name=weather-app
weather.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
weather.api.key=9ZHW3KS5YJRWH8RTXB27ZWXU7
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.org.springframework.cache=TRACE
spring.cache.type=redis
